# Generated by Django 4.1.3 on 2022-12-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkingMall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsType',
            field=models.CharField(choices=[('1', '女装'), ('2', '男装'), ('3', '食品'), ('4', '医药'), ('5', '日用'), ('6', '饰品'), ('7', '运动'), ('8', '电子'), ('9', '图书'), ('10', '其它')], max_length=20),
        ),
    ]
