# Generated by Django 4.1.3 on 2022-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkingMall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mailAddress',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mailAddress',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
