# Generated by Django 4.1.3 on 2022-12-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkingMall', '0002_alter_goods_goodstype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
