# Generated by Django 4.1.3 on 2022-12-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkingMall', '0003_rename_photos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receivingStatus',
            field=models.BooleanField(default=False),
        ),
    ]
