# Generated by Django 4.1.3 on 2022-12-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkingMall', '0004_order_receivingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='sellerName',
            field=models.CharField(max_length=40),
        ),
    ]
